A few more improvements

diff --git a/linaro-hwpack-install b/linaro-hwpack-install
--- a/linaro-hwpack-install
+++ b/linaro-hwpack-install
@@ -1,9 +1,25 @@
 #!/bin/sh
+# linaro-hwpack-install - Install a Linaro Hardware Pack.
 
-# XXX: Talk to James about files in sources.list.d having to end in .list and
-# about implausibly old time stamps (1969-12-31) in sample tarballs.
+# Copyright 2010 Linaro
+#
+# This program is free software: you can redistribute it and/or modify
+# it under the terms of the GNU General Public License version 3 as published
+# by the Free Software Foundation.
+#
+# This program is distributed in the hope that it will be useful,
+# but WITHOUT ANY WARRANTY; without even the implied warranty of
+# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+# GNU General Public License for more details.
+#
+# You should have received a copy of the GNU General Public License
+# along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
-#set -x
+
+# XXX: Not sure this is a good idea as there's some things we need to clean up
+# either on success or error.
+set -e
+
 LOCKFILE="/var/lock/hwpack"
 TEMP_DIR="/var/tmp/hwpack"
 HWPACK_DIR="/var/tmp/hwpack/unpacked"
@@ -18,6 +34,11 @@ clean_apt_sources() {
 
 # This creates all the directories we need.
 mkdir -p $HWPACK_DIR
+
+if [ $# -eq 0 ]; then
+  echo "Usage: `basename $0` HWPACK_URL"
+  exit 1
+fi
 
 (
 # Try to acquire fd #9 (i.e. /var/lock/hwpack) for 5 seconds.
@@ -42,7 +63,7 @@ HWPACK_ARCH=`grep ARCHITECTURE ${HWPACK_DIR}/metadata | cut -d "=" -f2`
 dpkg-architecture -e${HWPACK_ARCH}
 if [ $? -ne 0 ]; then
   echo "Hardware pack architecture ($HWPACK_ARCH) does not match the"\
-        "host's architecture"
+       "host's architecture"
   exit 1
 fi
 
@@ -75,15 +96,14 @@ cd $CWD
 sudo apt-get update -qq
 
 echo -n "Installing packages ..."
+  packages=`sed 's/ /=/' ${HWPACK_DIR}/manifest`
+  sudo apt-get -y install $packages
 # TODO:
-#   * run apt-get install to install the packages listed in the manifest
-#     * builds one long command line
-#     * iterate over packages in manifest
-#       * if package has version and --install-latest is not specified then add PACKAGE=VERSION to command line
-#       * else add PACKAGE to the command line
+#     * if package has version and --install-latest is not specified then add PACKAGE=VERSION to command line
+#     * else add PACKAGE to the command line
 #     * If there is an existing "/var/lib/hwpack/packages" it compares the list of packages it just installed with those listed in that file, and removes any in the file that it didn't just install itself.
-#       * TODO: how to safely remove the packages?
-#     * It then writes the list of packages that it installed to "/var/lib/hwpack/packages", overwriting any that were there already.
+#       * XXX: how to safely remove the packages?
+#     * Then write the list of packages that it installed to "/var/lib/hwpack/packages", overwriting any that were there already.
 echo "Done"
 
 clean_apt_sources
