Add a new --hwpack argument to linaro-media-create

diff --git a/linaro-media-create b/linaro-media-create
--- a/linaro-media-create
+++ b/linaro-media-create
@@ -22,7 +22,7 @@ set -e
 MLO_FILE=usr/lib/x-loader-omap/MLO
 UBOOT_FILE=usr/lib/u-boot/omap3_beagle/u-boot.bin
 
-unset MMC MMC1 MMC2 MMC3 IMAGE_FILE
+unset MMC MMC1 MMC2 MMC3 IMAGE_FILE HWPACK_FILE
 
 #Defaults
 RFS=ext3
@@ -37,8 +37,8 @@ IMAGE_SIZE=2G
 DIR=$PWD
 
 ensure_command() {
-# ensure_command foo foo-package
-which "$1" 2>/dev/null 1>/dev/null || ( echo "Installing required command $1 from package $2" && sudo apt-get install "$2" )
+  # ensure_command foo foo-package
+  which "$1" 2>/dev/null 1>/dev/null || ( echo "Installing required command $1 from package $2" && sudo apt-get install "$2" )
 }
 
 ensure_command sfdisk util-linux
@@ -95,6 +95,9 @@ Additional/Optional options:
 --console <ttyXY>
     add a console to kernel boot parameter; this parameter can be defined
     multiple times.
+
+--hwpack <filename>
+    A hardware pack that should be installed in the rootfs.
 
 --image_size nnnG or nnnM
     specify size of SD image to create; use with --image_file only (default: 2G)
@@ -183,6 +186,10 @@ while [ ! -z "$1" ]; do
       usage
       MMC=1
       ;;
+    --hwpack)
+      checkparm $2
+      HWPACK_FILE="$2"
+      ;;
     --mmc)
       checkparm $2
       MMC="$2"
@@ -262,29 +269,65 @@ esac
 RFS_UUID=`uuidgen -r`
 
 get_mmcs_by_id() {
-if [ ! ${IMAGE_FILE} ]; then
-  for device in /dev/disk/by-id/*; do
-    if [ `realpath $device` = $MMC ]; then
-      if echo "$device" | grep -q -- "-part[0-9]*$"; then
-        echo "device $MMC must not be a partition part ($device)" 1>&2
-        exit 1
-      fi
-      for part_id in `ls "$device-part"*`; do
-        part=`realpath $part_id`
-        part_no=`echo $part_id | sed -e 's/.*-part//g'`
-        # echo "part $part_no found: $part_id" 1>&2
-        if test "$part_no" = 1; then
-          MMC1=$part
-        elif test "$part_no" = 2; then
-          MMC2=$part
-        elif test "$part_no" = 3; then
-          MMC3=$part
+  if [ ! ${IMAGE_FILE} ]; then
+    for device in /dev/disk/by-id/*; do
+      if [ `realpath $device` = $MMC ]; then
+        if echo "$device" | grep -q -- "-part[0-9]*$"; then
+          echo "device $MMC must not be a partition part ($device)" 1>&2
+          exit 1
         fi
-      done
-      break
-    fi
-  done
-fi
+        for part_id in `ls "$device-part"*`; do
+          part=`realpath $part_id`
+          part_no=`echo $part_id | sed -e 's/.*-part//g'`
+          # echo "part $part_no found: $part_id" 1>&2
+          if test "$part_no" = 1; then
+            MMC1=$part
+          elif test "$part_no" = 2; then
+            MMC2=$part
+          elif test "$part_no" = 3; then
+            MMC3=$part
+          fi
+        done
+        break
+      fi
+    done
+  fi
+}
+
+install_hwpack_into_tarball() {
+  ensure_command qemu-arm-static qemu-arm-static
+
+  mkdir hwpack-tmp
+  sudo tar -xf $BINARY_TARBALL -C ${DIR}/hwpack-tmp/
+
+  # XXX: Assume linaro-hwpack-install lives on the same directory as this
+  # script. This is far from optimal but should do for now.
+  LINARO_HWPACK_INSTALL=$(dirname $0)/linaro-hwpack-install
+
+  chroot=${DIR}/hwpack-tmp/binary
+  sudo mv ${chroot}/etc/resolv.conf ${DIR}/resolv.conf.orig
+  sudo cp /etc/resolv.conf ${chroot}/etc/resolv.conf
+
+  sudo mv ${chroot}/etc/hosts ${DIR}/hosts.orig
+  sudo cp /etc/hosts ${chroot}/etc/hosts
+
+  sudo cp /usr/bin/qemu-arm-static ${chroot}/usr/bin
+  sudo cp $LINARO_HWPACK_INSTALL ${chroot}/usr/bin
+  sudo cp "$HWPACK_FILE" "$chroot"
+
+  sudo chroot "$chroot" mount proc /proc -t proc
+  sudo chroot "$chroot" linaro-hwpack-install /$(basename "$HWPACK_FILE")
+  sudo chroot "$chroot" umount /proc
+
+  sudo mv -f ${DIR}/resolv.conf.orig ${chroot}/etc/resolv.conf
+  sudo mv -f ${DIR}/hosts.orig ${chroot}/etc/hosts
+  sudo rm -f ${chroot}/usr/bin/qemu-arm-static
+  sudo rm -f ${chroot}/usr/bin/linaro-hwpack-install
+  sudo rm -f ${chroot}/$(basename "$HWPACK_FILE")
+
+  tar cf binary-with-hwpack.tar -C hwpack-tmp/ .
+  sudo rm -rf hwpack-tmp/
+  BINARY_TARBALL=${DIR}/binary-with-hwpack.tar
 }
 
 prepare_sources() {
@@ -480,7 +523,7 @@ populate_rootfs() {
       sudo dd if=/dev/zero of=${DIR}/disk/SWAP.swap bs=1M count=$SWAP_SIZE
       sudo mkswap ${DIR}/disk/SWAP.swap
       echo "/SWAP.swap  none  swap  sw  0 0" | sudo tee -a ${DIR}/disk/etc/fstab
-      else
+    else
       echo "SWAP file bigger then whats left on partition"
     fi
   fi
@@ -578,6 +621,11 @@ if [ ! "${MMC}" -a ! "${IMAGE_FILE}" ]; then
   usage
 fi
 
+ if [ "$HWPACK_FILE" ]; then
+   # This will unpack the binary tarball, install the hwpack in it, tar it up
+   # again and make this script use that new tarball from now on.
+   install_hwpack_into_tarball
+ fi
  prepare_sources
  get_mmcs_by_id
  cleanup_sd
